/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/element_ref';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
class SignaturePadModuleInjector extends import0.NgModuleInjector<import1.SignaturePadModule> {
  _SignaturePadModule_0:import1.SignaturePadModule;
  constructor(parent:import2.Injector) {
    super(parent,[],[]);
  }
  createInternal():import1.SignaturePadModule {
    this._SignaturePadModule_0 = new import1.SignaturePadModule();
    return this._SignaturePadModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SignaturePadModule)) { return this._SignaturePadModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SignaturePadModuleNgFactory:import0.NgModuleFactory<import1.SignaturePadModule> = new import0.NgModuleFactory(SignaturePadModuleInjector,import1.SignaturePadModule);
var renderType_SignaturePad_Host:import3.RenderComponentType = (null as any);
class _View_SignaturePad_Host0 extends import4.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _SignaturePad_0_4:import1.SignaturePad;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import2.Injector,declarationEl:import5.AppElement) {
    super(_View_SignaturePad_Host0,renderType_SignaturePad_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('signature-pad',rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignaturePad0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignaturePad_0_4 = new import1.SignaturePad(new import9.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._SignaturePad_0_4,[],compView_0);
    compView_0.create(this._SignaturePad_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SignaturePad) && (0 === requestNodeIndex))) { return this._SignaturePad_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._SignaturePad_0_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignaturePad_Host0(viewUtils:import6.ViewUtils,parentInjector:import2.Injector,declarationEl:import5.AppElement):import4.AppView<any> {
  if ((renderType_SignaturePad_Host === (null as any))) { (renderType_SignaturePad_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SignaturePad_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignaturePadNgFactory:import11.ComponentFactory<import1.SignaturePad> = new import11.ComponentFactory<import1.SignaturePad>('signature-pad',viewFactory_SignaturePad_Host0,import1.SignaturePad);
const styles_SignaturePad:any[] = [];
var renderType_SignaturePad:import3.RenderComponentType = (null as any);
class _View_SignaturePad0 extends import4.AppView<import1.SignaturePad> {
  _el_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import2.Injector,declarationEl:import5.AppElement) {
    super(_View_SignaturePad0,renderType_SignaturePad,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'canvas',(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_SignaturePad0(viewUtils:import6.ViewUtils,parentInjector:import2.Injector,declarationEl:import5.AppElement):import4.AppView<import1.SignaturePad> {
  if ((renderType_SignaturePad === (null as any))) { (renderType_SignaturePad = viewUtils.createRenderComponentType('/Users/brian/Developer/Mobile/angular2-signaturepad/index.ts class SignaturePad - inline template',0,import10.ViewEncapsulation.None,styles_SignaturePad,{})); }
  return new _View_SignaturePad0(viewUtils,parentInjector,declarationEl);
}